title: WhatsApp Bot Documentation
description: Comprehensive guide for WhatsApp bot implementation
baseurl: "/baileys-rise" # ganti dengan nama repo Anda
url: "https://clayzaaubert.github.io" # ganti dengan username GitHub Anda

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins yang kompatibel dengan GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Theme settings
theme_color: "#25D366"
accent_color: "#128C7E"

# SEO
author: Clayza Aubert
twitter:
  username: your_twitter
  card: summary

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md