source "https://rubygems.org"

# Gunakan github-pages gem untuk kompatibilitas penuh
gem "github-pages", group: :jekyll_plugins

# Atau jika ingin manual:
# gem "jekyll", "~> 3.9.0"
# gem "jekyll-feed", "~> 0.15"
# gem "jekyll-sitemap", "~> 1.4"
# gem "jekyll-seo-tag", "~> 2.8"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]